<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <title>Ошибка</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="icon" href="https://drive.google.com/drive/u/0/folders/1a8UV1i3yiDBXtM-HutFS-hjwUb6UJjQP">
</head>
<body class=" m-0 border-0 font-monospace" style="font-family: 'Ysabeau', sans-serif;">
<div class="container mt-4">
    <div style="text-align: center">
        <br>
        <h1>УПС...</h1>
        <br>
        <h2>Кажется что-то пошло не так...</h2>
        <br>
        <h3>Страница не найдена</h3>
    </div>
    <br>
    <div class="d-grid gap-2">
        <a href="/" class="btn btn-outline-info" role="button">Вернуться на главную страницу</a>
    </div>
</div>
</body>
</html>